
function f_gval(a){return(a=document.getElementById(a))?a.value:null}function f_sval(a,c){var b=document.getElementById(a);if(!b)return!1;b.color&&b.color.fromString?b.color.fromString(c):b.value=c;return!0};
var _zoom_factor=1,_zoom_value=100;function tp_set_zoom(a){a!=_zoom_factor&&(_zoom_value=Math.min(Math.max(a,25),200),_zoom_factor=_zoom_value/100,update_viewport())}function tp_toggle_autozoom_marker(a){var b=document.getElementById("zoom-autozoom-marker");b&&(b.style.visibility=a?"visible":"hidden")}
function tp_init_zoom(){var a=window,b=document,c=b.documentElement,d=b.getElementsByTagName("body")[0],b=a.innerWidth||c.clientWidth||d.clientWidth,a=a.innerHeight||c.clientHeight||d.clientHeight,b=Math.max(b-262,800),a=Math.max(a-100,800);if(_original_image_width<=b&&_original_image_height<=a)update_zoom_select();else for(c=document.getElementById("zoom-selectbox"),d=0;d<c.options.length;d++){var e=c.options[d].value;if(100>e){var f=e/100;if(_original_image_width*f<=b&&_original_image_height*f<=
a){tp_set_zoom(e);tp_toggle_autozoom_marker(!0);break}}}}
function update_viewport(){var a=zoom(_original_image_width),b=zoom(_original_image_height);set_size("rendered-image",a,b);set_size("ca-canvas",a,b);set_size("textlayer",a,b);set_size("image-container",a,b);set_size("image-container-wrapper",a,b);a=zoom(_original_base_width);b=zoom(_original_base_height);set_size("fsdlg-baseimage",a,b);set_size("cropUI",a,b);if(resizeUI)resizeUI.onZoomChanged();if(chiRegion)chiRegion.onZoomChanged();if(annotateUI)annotateUI.onZoomChanged();update_zoom_select()}
function update_zoom_select(){var a=document.getElementById("zoom-selectbox");if(a)for(var b=0;b<a.options.length;b++)if(a.options[b].value==_zoom_value){a.selectedIndex=b;break}}function zoom(a){return Math.round(a*_zoom_factor)}function unzoom(a){return Math.round(a/_zoom_factor)}function set_size(a,b,c){"string"==typeof a&&(a=document.getElementById(a));a&&("image"==typeof a&&(a.width=b,a.height=c),a.style.width=b+"px",a.style.height=c+"px")}
function applyeffect(a,b){if(a){var c=document.getElementById("effect-cascade2");if(c)return c.action="/photo-effects/"+a,b&&(c.elements.src.value=""),c.submit(),!1}}function addEvent(a,b,c){return a.addEventListener?(a.addEventListener(b,c,!1),!0):a.attachEvent?a.attachEvent("on"+b,c):!1}function setStyle(a,b){a.style&&a.style.setAttribute?a.style.cssText=a.style.cssText+";"+b:a.setAttribute("style",a.style.cssText+";"+b)}var nzindex=0;
function bringElementToTop(a){!a||!a.style||a.style.zIndex>=nzindex||(nzindex++,a.style.zIndex=nzindex)}function new_xmlhttp(){var a=null;try{a=new XMLHttpRequest}catch(b){try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(d){wsq_request=null}}}return a}function rfalse(){return!1}
function urlencode_form(a){for(var b="",c=0;c<a.elements.length;c++)if(a.elements[c]&&a.elements[c].name&&("checkbox"!=a.elements[c].type&&"radio"!=a.elements[c].type||a.elements[c].checked))var d=a.elements[c].value,b=b+(a.elements[c].name+"="),b=b+encodeURIComponent(d),b=b+"&";return b}function setInputImage(a){if(wsEffect){var b=document.getElementById("set-input-image-form");b&&(b.elements.src.value=a,b.submit())}}
function submitFilterSettings(){document.getElementById("filter-settings").submit()}function download_dlg(a,b){txlog("Shared",wsEffect);var c=window.open("/share/"+a+"/start/"+b,"ExportDlg","width=580,height=440,top=120,left=60,scrollbars=yes");setTimeout(function(){try{c.focus()}catch(a){}},800);return!1}
function update_downloadlinks(a){a=a.replace(/\.jpe?g$/i,"");for(var b=[{t:"download",href:"/share/download/"+a},{t:"facebook",onclick:function(){return download_dlg("facebook",a)}},{t:"imageshack",onclick:function(){return download_dlg("imageshack",a)}},{t:"imgur",onclick:function(){return download_dlg("imgur",a)}}],c=0;c<b.length;c++)for(var d=b[c],e=null,f=0;e=document.getElementById("download-option-"+d.t+f);f++)d.href&&(e.href=d.href),d.onclick&&(e.href="#",e.onclick=d.onclick)}
var ddp_reqobj=new_xmlhttp(),ddp_active="";function ddp_filters(a){ddp_toggle("/ddp/filters/"+a,!0)}function ddp_workingset(a,b){ddp_toggle("/queryWorkingset?wsid="+a+"&effect="+b,!1)}
function ddp_toggle(a,b){if(a==ddp_active){var c=document.getElementById("editorUI-ddp-anchor");if(!c||"block"==c.style.display)return;if(b){TPEditorUI.cancelUI();c.style.display="block";return}}ddp_active=a;c=ddp_reqobj;TPEditorUI.showLoadIndicator(!0);c.open("GET",a,!0);c.onreadystatechange=ddp_onreadystatechange;c.send(null);return!1}function ddp_close(){var a=document.getElementById("editorUI-ddp-anchor");a&&(a.style.display="none")}
function ddp_onreadystatechange(){var a=ddp_reqobj;a&&4==a.readyState&&(TPEditorUI.showLoadIndicator(!1),TPEditorUI.cancelUI(),200==a.status&&ddp_setcontent(a.responseText))}function ddp_setcontent(a){var b=document.getElementById("editorUI-ddp-anchor");b&&(b.innerHTML=a,b.style.display="block")}var RH_NORTH=1,RH_EAST=2,RH_SOUTH=4,RH_WEST=8,RH_DRAG=-1;
function CrRHelper(a,b){this._roffB=this._roffR=this._roffT=this._roffL=this._roffY=this._roffX=this._flags=0;this._element=null;this._idPrefix=a?a:"crUI-";this._knobHeight=this._knobWidth=10;this._idCregion=this._idPrefix+"cregion";this._idContainer=this._idPrefix+"container";this._idElement=null;this._asratio=this._flags=this._startH=this._startW=0;this._minHeight=this._minWidth=20;this._maskID=b?this._idPrefix+"mask":null;this._maskUrl=b;this._center=!0}
CrRHelper.prototype.flags2str=function(a){var b="";a&RH_NORTH&&(b+="n");a&RH_SOUTH&&(b+="s");a&RH_WEST&&(b+="w");a&RH_EAST&&(b+="e");return b};CrRHelper.prototype.createKnob=function(a,b){var c=this.flags2str(b),d=document.createElement("div");d.setAttribute("id",this._idPrefix+"knob-"+c);d.className="cropUI-resizehandle";d.style.cursor=c+"-resize";d.style.width=this._knobWidth+"px";d.style.height=this._knobHeight+"px";d.onmousedown=delegate_event1(this,"onmousedown",b);a.appendChild(d)};
CrRHelper.prototype.createOverlay=function(a,b){var c=document.createElement("div");c.setAttribute("id",this._idPrefix+"cropUI-overlay-"+b);c.className="cropUI-overlay";c.style.zIndex=1E4;a.appendChild(c)};
CrRHelper.prototype.attach=function(a,b){if(!a)return!1;this._isCrop=b;this._flags=0;this._element=a;this._idElement=a.id;this._startW=a.offsetWidth;this._startH=a.offsetHeight;this._aspectratio=this._startH/this._startW;this._keepAspectratio=1;var c=document.createElement("div");c.setAttribute("id",this._idContainer);c.style.position="relative";c.style.width=this._startW+"px";c.style.height=this._startH+"px";c.onselectstart=rfalse;c.onmousedown=rfalse;c.onclick=function(){return!0};var d=null;this._maskUrl&&
(d=document.createElement("img"),d.setAttribute("id",this._maskID),d.style.position="absolute",d.style.left="0px",d.style.top="0px",d.style.width=this._startW+"px",d.style.height=this._startH+"px",d.src=this._maskUrl);var e=document.createElement("div");e.setAttribute("id",this._idCregion);e.className="crUI-cregion";e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.onselectstart=rfalse;e.style.width=this._startW+"px";e.style.height=this._startH+"px";b&&(e.onmousedown=delegate_event1(this,
"onmousedown",RH_DRAG),e.style.cursor="move");this.createKnob(e,RH_NORTH|RH_WEST);this.createKnob(e,RH_NORTH);this.createKnob(e,RH_NORTH|RH_EAST);this.createKnob(e,RH_EAST);this.createKnob(e,RH_SOUTH|RH_EAST);this.createKnob(e,RH_SOUTH);this.createKnob(e,RH_SOUTH|RH_WEST);this.createKnob(e,RH_WEST);this._isCrop&&(this.createOverlay(c,"n"),this.createOverlay(c,"e"),this.createOverlay(c,"s"),this.createOverlay(c,"w"));var f=a.parentNode,g=a.nextSibling;c.appendChild(a);d&&c.appendChild(d);c.appendChild(e);
f.insertBefore(c,g);e.style.display="block";c.style.display="block";b?(c=parseInt(.2*this._startW),d=parseInt(.2*this._startH),this.resize(c,d,this._startW-2*c,this._startH-2*d)):this.resize(0,0,this._startW,this._startH)};
CrRHelper.prototype.onZoomChanged=function(){var a=this._element.offsetWidth,b=this._element.offsetHeight;if(this._startW!=a||this._startH!=b){var c=a/this._startW,d=b/this._startH,e=this.dimensions();set_size(this._idContainer,a,b);this._startW=a;this._startH=b;this.resize(Math.round(e.left*c),Math.round(e.top*d),Math.round((e.right-e.left)*c),Math.round((e.bottom-e.top)*d))}};
CrRHelper.prototype.detach=function(){try{var a=document.getElementById(this._idElement),b=document.getElementById(this._idContainer);b.parentNode.insertBefore(a,b);b.parentNode.removeChild(b)}catch(c){throw"CrHelper::detach: "+c;}};CrRHelper.prototype.reset=function(){this.resize(0,0,this._startW,this._startH)};
CrRHelper.prototype.onmousedown=function(a,b){if(this._flags||!b)return!1;var c=0,d=0;a||(a=window.event);if(a.pageX||a.pageY)c=a.pageX,d=a.pageY;else if(a.clientX||a.clientY)c=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;this._flags=b;document.onmousemove=delegate_event(this,"onmousemove");document.onmouseup=delegate_event(this,"onmouseup");this._roffX=c;this._roffY=d;c=document.getElementById(this._idCregion);
this._roffL=parseInt(c.style.left);this._roffT=parseInt(c.style.top);d=c.offsetHeight;this._roffR=this._roffL+c.offsetWidth;this._roffB=this._roffT+d;d=document.getElementById(this._idContainer);this._flags!=RH_DRAG&&(d.style.cursor=c.style.cursor=this.flags2str(this._flags)+"-resize");return!1};
CrRHelper.prototype.onmouseup=function(a){if(!this._flags)return!1;this._flags=0;document.onmousemove=null;document.onmouseup=null;a=document.getElementById(this._idContainer);var b=document.getElementById(this._idCregion);a.style.cursor="auto";b.style.cursor=this._isCrop?"move":"auto";return!1};
CrRHelper.prototype.onmousemove=function(a){var b=this._flags;if(!b)return!1;var c=0,d=0;a||(a=window.event);if(a.pageX||a.pageY)c=a.pageX,d=a.pageY;else if(a.clientX||a.clientY)c=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,d=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;var e=document.getElementById(this._idCregion),f=document.getElementById(this._idContainer),g=parseInt(e.style.left);a=parseInt(e.style.top);var h=g+parseInt(e.style.width),e=a+parseInt(e.style.height),
k=h-g,l=e-a,c=c-this._roffX,d=d-this._roffY;this._isCrop&&this._flags==RH_DRAG?(g=this._roffL+c,0>g&&(g=0),g+k>f.offsetWidth&&(g=f.offsetWidth-k),h=g+k,a=this._roffT+d,0>a&&(a=0),a+l>f.offsetHeight&&(a=f.offsetHeight-l),e=a+l):(b&RH_NORTH&&(a=this._roffT+d),b&RH_EAST&&(h=this._roffR+c),b&RH_SOUTH&&(e=this._roffB+d),b&RH_WEST&&(g=this._roffL+c),e<a&&(b=this._flags=b&(RH_EAST|RH_WEST)|(b&RH_NORTH?RH_SOUTH:RH_NORTH),d=this._roffB,this._roffB=this._roffT,this._roffT=d),h<g&&(this._flags=b&(RH_NORTH|RH_SOUTH)|
(b&RH_WEST?RH_EAST:RH_WEST),d=this._roffR,this._roffR=this._roffL,this._roffL=d));a=Math.max(Math.min(a,f.offsetHeight),0);g=Math.max(Math.min(g,f.offsetWidth),0);e=Math.max(Math.min(e,f.offsetHeight),0);h=Math.max(Math.min(h,f.offsetWidth),0);if(30>h-g||30>e-a)return!1;b=Math.min(g,h);g=Math.max(g,h);h=Math.min(a,e);a=Math.max(a,e);this.resize(b,h,g-b,a-h);return!1};
CrRHelper.prototype.resize=function(a,b,c,d){var e=b;b=c;var f=d;this._isCrop||(this._keepAspectratio&&(a=0>f?-1:1,f=b*this._aspectratio,f=parseInt(f+.5),f=Math.abs(f)*a),e=document.getElementById(this._idContainer),a=.5*e.offsetWidth-.5*b,e=.5*e.offsetHeight-.5*f,a=parseInt(a),parseInt(e),e=0,b=parseInt(b),f=parseInt(f));this._center||(e=a=0);var g="left:"+a+"px;top:"+e+"px;width:"+b+"px;height:"+f+"px;",h=document.getElementById(this._idCregion);setStyle(h,g);this._maskID&&(h=document.getElementById(this._maskID),
setStyle(h,g));c=1/(this._startW/c);d=1/(this._startH/d);this._onresize&&this._onresize(this,a,e,b,f,c,d);this.positionKnobs()};
CrRHelper.prototype.positionKnobs=function(){var a=document.getElementById(this._idCregion),b=parseInt(a.style.width),c=parseInt(a.style.height),d=this._knobWidth,e=this._knobHeight,f=null,g=0,h=0,k=this._idPrefix+"knob-",l="visibility:"+(this._keepAspectratio?"hidden;":"visible;");(f=document.getElementById(k+"nw"))&&setStyle(f,"left:0px;top:0px;");if(f=document.getElementById(k+"n"))g=parseInt(.5*b-.5*d),setStyle(f,"left:"+g+"px;top:0px;"+l);(f=document.getElementById(k+"ne"))&&setStyle(f,"left:"+
(b-d)+"px;top:0px;");if(f=document.getElementById(k+"e"))g=b-d,h=parseInt(.5*c-.5*e),setStyle(f,"left:"+g+"px;top:"+h+"px;"+l);(f=document.getElementById(k+"se"))&&setStyle(f,"left:"+(b-d)+"px;top:"+(c-e)+"px;");if(f=document.getElementById(k+"s"))g=parseInt(.5*b-.5*d),setStyle(f,"left:"+g+"px;top:"+(c-e)+"px;"+l);(f=document.getElementById(k+"sw"))&&setStyle(f,"left:0px;top:"+(c-e)+"px;");if(f=document.getElementById(k+"w"))g=0,h=parseInt(.5*c-.5*e),setStyle(f,"left:"+g+"px;top:"+h+"px;"+l);this._isCrop&&
(d=null,e=this._startW,f=this._startH,g=parseInt(a.style.left),a=parseInt(a.style.top),d=document.getElementById(this._idPrefix+"cropUI-overlay-n"),setStyle(d,"left:0px;top:0px;width:"+e+"px;height:"+a+"px;"),d=document.getElementById(this._idPrefix+"cropUI-overlay-e"),setStyle(d,"left:"+(g+b)+"px;top:"+a+"px;width:"+(e-(g+b))+"px;height:"+c+"px;"),d=document.getElementById(this._idPrefix+"cropUI-overlay-s"),setStyle(d,"left:0px;top:"+(a+c)+"px;width:"+e+"px;height:"+(f-(a+c))+"px;"),d=document.getElementById(this._idPrefix+
"cropUI-overlay-w"),setStyle(d,"left:0px;top:"+a+"px;width:"+g+"px;height:"+c+"px;"))};CrRHelper.prototype.keepAspectratio=function(a){this._keepAspectratio=a;this.positionKnobs()};CrRHelper.prototype.getWidth=function(){var a=document.getElementById(this._idCregion);return parseInt(a.style.width)};CrRHelper.prototype.getHeight=function(){var a=document.getElementById(this._idCregion);return parseInt(a.style.height)};
CrRHelper.prototype.dimensions=function(){var a=document.getElementById(this._idCregion),b={};b.left=parseInt(a.style.left);b.top=parseInt(a.style.top);b.right=b.left+parseInt(a.style.width);b.bottom=b.top+parseInt(a.style.height);return b};
var resizeUI={_prefix:"crUI-",_containerId:"textlayer",_cropregionId:"crUI-cropregion",_resizer:null,_originalWidth:0,_originalHeight:0,onresize:function(a,b,c,d,e,f,g){a=document.getElementById("rendered-image");setStyle(a,"position:absolute;left:"+b+"px;top:"+c+"px;width:"+d+"px;height:"+e+"px")},startResize:function(){TPEditorUI.cancelUI();tp_set_zoom(100);resizeUI.showDropdown(!0,!1);resizeUI._resizer=new CrRHelper;resizeUI._resizer._center=!1;resizeUI._resizer._onresize=function(a,b,c,d,e,f,
g){resizeUI.onresize(a,b,c,d,e,f,g)};resizeUI._resizer.attach(document.getElementById("image-container"),!1);annotateUI.showTextlayer(!1)},onZoomChanged:function(){if(resizeUI._resizer)resizeUI._resizer.onZoomChanged()},startCrop:function(){TPEditorUI.cancelUI();resizeUI.showDropdown(!0,!0);resizeUI._resizer=new CrRHelper;resizeUI._resizer.attach(document.getElementById("image-container"),!0);annotateUI.showTextlayer(!1)},startRotate:function(){TPEditorUI.cancelUI();var a=document.getElementById("toolbar-dropdown");
if(!a)return!1;a.innerHTML='<a href="#" onclick="TPEditorUI.cancelUI();return false" class="editor-panel-ctrlbar-close"></a><div class="toolbar-rotate"> <a href="#" onclick="resizeUI.doRotate(1);return false"><img src="/static/images/t.gif" alt="Rotate Left" width="42" height="42" class="tbb-rotate-left"></a> <a href="#" onclick="resizeUI.doRotate(2);return false"><img src="/static/images/t.gif" alt="Rotate Right" width="42" height="42" class="tbb-rotate-right"></a> <a href="#" onclick="resizeUI.doRotate(3);return false"><img src="/static/images/t.gif" alt="Flip Horizontal" width="42" height="42" class="tbb-rotate-flop"></a> <a href="#" onclick="resizeUI.doRotate(4);return false"><img src="/static/images/t.gif" alt="Flip Vertical" width="42" height="42"  class="tbb-rotate-flip"></a></div>';
a.style.display="block"},doRotate:function(a){document.getElementById("effect-cascade2").elements.efp_postrotate.value=a;applyeffect("rotate",!1)},showDropdown:function(a,b){var c=document.getElementById("toolbar-dropdown");if(!c)return!1;if(a){var d=document.getElementById("rendered-image");resizeUI._originalWidth=d.offsetWidth;resizeUI._originalHeight=d.offsetHeight;var d="resizeUI.applyResize()",e="Apply",f='<a href="#" onclick="TPEditorUI.cancelUI();return false" class="editor-panel-ctrlbar-close"></a>';
if(b)d="resizeUI.applyCrop()",e="Apply";else{for(var g=1,h="",k=0;4>k;k++){var l="";switch(k){case 3:l="Original Size";g=1;break;case 2:l="75%";g=.75;break;case 1:l="50%";g=.5;break;case 0:l="25%",g=.25}var m=Math.round(_original_image_width*g),n=Math.round(_original_image_height*g);if(30>m||30>n)break;h&&(h+=" | ");h+='<a href="#" onclick="resizeUI.setPredefined('+m+","+n+');return false"><em>'+l+'</em> <span class="resizebar-preset-size">('+m+"x"+n+")</span></a>"}f+='<div class="resizebar-ctrls"><span class="resizebar-input"><input type="checkbox" id="crUI-keep-aspect-ratio" checked value="1" onclick="resizeUI.keepAspectratio(this.checked)"><label class="checkbox" for="crUI-keep-aspect-ratio">Keep aspect ratio</label></span>';
f+='<span class="resizebar-presets">'+h+'<input type="checkbox" style="visibility:hidden;"</span>';f+="</div>"}f+='<div class="resizebar-confirm"><button class="confirm" onclick="'+d+';return false">'+e+"</button>";c.innerHTML=f;c.style.display="block"}else c.innerHTML="",c.style.display="none"},setSize:function(a,b){resizeUI._resizer&&resizeUI._resizer.resize(0,0,a,b);return!1},setPredefined:function(a,b){tp_set_zoom(100);resizeUI.setSize(a,b);return!1},keepAspectratio:function(a){resizeUI._resizer&&
resizeUI._resizer.keepAspectratio(a)},applyResize:function(){var a=document.getElementById("effect-cascade2");a.action="/photo-effects/resize";this._resizer.dimensions();var b=create_input_hidden(a,"efp_transform_resizeW"),c=create_input_hidden(a,"efp_transform_resizeH");b.value=unzoom(resizeUI._resizer.getWidth());c.value=unzoom(resizeUI._resizer.getHeight());a.submit()},applyCrop:function(){var a=document.getElementById("effect-cascade2");a.action="/photo-effects/crop";var b=this._resizer.dimensions(),
c=create_input_hidden(a,"efp_transform_cropL"),d=create_input_hidden(a,"efp_transform_cropT"),e=create_input_hidden(a,"efp_transform_cropR"),f=create_input_hidden(a,"efp_transform_cropB");c.value=unzoom(b.left);d.value=unzoom(b.top);e.value=unzoom(b.right);f.value=unzoom(b.bottom);a.submit()},cancelUI:function(){try{document.getElementById("ca-canvas").style.display="none",annotateUI.showTextlayer(!0)}catch(a){}resizeUI.showDropdown(!1);resizeUI._resizer&&(resizeUI._resizer.reset(),resizeUI._resizer.detach(),
resizeUI._resizer=null,document.getElementById("rendered-image").style.position="static",annotateUI.resizeTextLayer(0,0,resizeUI._originalWidth,resizeUI._originalHeight,1,1),annotateUI.showTextlayer(!0))}};function chiRegion_show(a,b,c,d,e){chiRegion.show(a,b,c,d,e)}
function shapeMask_startUI(a,b,c,d,e){TPEditorUI.cancelUI();var f=document.getElementById("editorUI-mask-input");f.style.display="block";for(var g=0,h=null;(h=document.getElementById("efp-shape"+g))&&!h.checked;)g++;var k=null;h&&(k="/static/images/"+a+"/shape-masks/"+b+"/"+g+".png");chiRegion.show(f,c,d,e,0,k);f.style.display="block"}
function shapeMask_setmask(a,b,c){document.getElementById("efp-shape"+c).checked=!0;var d=null;(d=document.getElementById("choose-input-regionmask"))?d.src="/static/images/"+a+"/shape-masks/"+b+"/"+c+".png":qru_do()}
var chiRegion={_formID:"filter-settings-form",_formElementRegion:"efp_cropinput",_formElementMode:"efp_chir_mode",_idModeSelect:"chiRegion-mode",_resizer:null,show:function(a,b,c,d,e,f){TPEditorUI.cancelUI();if(chiRegion._resizer)return!1;var g=document.getElementById(chiRegion._formID);if(!g)return!1;e=parseInt(g.elements.efp_mask_left.value);var h=parseInt(g.elements.efp_mask_top.value),k=parseInt(g.elements.efp_mask_right.value)-e,g=parseInt(g.elements.efp_mask_bottom.value)-h;0<k&&0<g||(e=parseInt(.2*
c),h=parseInt(.2*d),k=c-2*e,g=d-2*h);var l="",l='<div class="cropUI-controls"> <button onClick="chiRegion.submit(); return false" class="confirm">Apply</button></div><div id="cropUI" style="width:'+c+'px;"><a href="#" onclick="TPEditorUI.cancelUI();return false" class="editor-panel-ctrlbar-close"></a><div id="cropUI-container" style="width:'+c+"px;height:"+d+'px;"><img src="'+b+'" id="fsdlg-baseimage" width="'+c+'" height="'+d+'" alt=""></div></div>';a.innerHTML=l;chiRegion._resizer=new CrRHelper("choose-input-region",
f);chiRegion._resizer.attach(document.getElementById("fsdlg-baseimage"),!0);chiRegion._resizer.resize(e,h,k,g);update_viewport();return!1},cancelUI:function(){chiRegion._resizer&&(chiRegion._resizer.detach(),chiRegion._resizer=null,document.getElementById("editorUI-mask-input").style.display="none")},submit:function(){if(chiRegion._resizer){var a=chiRegion._resizer.dimensions(),b=document.getElementById(chiRegion._formID);b.elements.efp_mask_top.value=unzoom(a.top);b.elements.efp_mask_bottom.value=
unzoom(a.bottom);b.elements.efp_mask_right.value=unzoom(a.right);b.elements.efp_mask_left.value=unzoom(a.left);annotateUI.storeToForm(chiRegion._formID);b.submit()}},cancel:function(){var a=document.getElementById(chiRegion._formID);a.elements[chiRegion._formElementRegion].value="";a.elements[chiRegion._formElementMode].value=0;a.submit()},onZoomChanged:function(){if(chiRegion._resizer)chiRegion._resizer.onZoomChanged()}},DragHandler={_oElem:null,_container:null,ondragend:null,ondragbegin:null,attach:function(a,
b){if(a)return DragHandler._container=b,a.onmousedown=DragHandler._dragBegin,a=a.parentNode,a.dragBegin=new Function,a.drag=new Function,a.dragEnd=new Function,a},_dragBegin:function(a){var b=DragHandler._oElem=this.parentNode;if(b){DragHandler.ondragbegin&&DragHandler.ondragbegin.call();isNaN(parseInt(b.style.left))&&(b.style.left="0px");isNaN(parseInt(b.style.top))&&(b.style.top="0px");var c=parseInt(b.style.left),d=parseInt(b.style.top);a=a?a:window.event;b.mouseX=a.clientX;b.mouseY=a.clientY;
bringElementToTop(b);b.dragBegin(b,c,d);document.onmousemove=DragHandler._drag;document.onmouseup=DragHandler._dragEnd;return!1}},_drag:function(a){var b=DragHandler._oElem;if(!b)return!1;var c=parseInt(b.style.left),d=parseInt(b.style.top);a=a?a:window.event;var e=c+a.clientX-b.mouseX,f=d+a.clientY-b.mouseY,g=0,h=0;if(DragHandler._container){var k=DragHandler._container.offsetWidth-b.offsetWidth;e>k&&(g=k-e,e=k);k=DragHandler._container.offsetHeight-b.offsetHeight;f>k&&(h=k-f,f=k);0>e&&(g=-e,e=0);
0>f&&(h=-f,f=0)}b.style.left=e+"px";b.style.top=f+"px";b.mouseX=a.clientX+g;b.mouseY=a.clientY+h;b.drag(b,c+g,d+h);return!1},_dragEnd:function(){var a=DragHandler._oElem;if(a){var b=parseInt(a.style.left),c=parseInt(a.style.top);a.dragEnd(a,b,c)}document.onmousemove=null;document.onmouseup=null;DragHandler._oElem=null;DragHandler.ondragend&&DragHandler.ondragend.call(a)}};
function request_sticker_image(a){var b=new_xmlhttp();b&&(TPEditorUI.showLoadIndicator(!0),b.open("GET",annotateUI._imgURL(a),!0),b.onreadystatechange=function(){request_sticker_image_rstc(b,a)},b.setRequestHeader("Content-type","application/x-www-form-urlencoded"),b.send())}
function request_sticker_image_rstc(a,b){if(a&&4==a.readyState&&200==a.status){TPEditorUI.showLoadIndicator(!1);var c=a.responseText.split(",");if(3==c.length){var d=parseInt(c[0]),e=parseInt(c[1]),f=document.getElementById(b._nodeId),g=document.getElementById(b._nodeId+"-img");g.src="data:image/png;base64,"+c[2];f.annotateUI_textProperties._zoom_factor=_zoom_factor;f.annotateUI_textProperties._org_image_width=d;f.annotateUI_textProperties._org_image_height=e;c=zoom(d);e=zoom(e);set_size(g,c,e);set_size(f,
c,e)}}}
var annotateUI={_nextID:1,_activeElement:null,_controlsTimerId:null,_textNodes:[],_countTextElements:0,_stateTimerId:0,_stateNotification:new_xmlhttp(),_stateFetcher:new_xmlhttp(),toggleUI:function(){TPEditorUI.cancelUI();document.getElementById("annotateUI-panel").style.display="block";var a=document.getElementById("annotateUI-text");a&&a.focus()},onZoomChanged:function(){var a=document.getElementById("textlayer");if(a){for(var a=a.firstChild,b=0;a;){var c=a.firstChild;if(c&&c.annotateUI_textProperties&&c.annotateUI_textProperties._zoom_factor&&
c.annotateUI_textProperties._nodeId){var d=c.annotateUI_textProperties._zoom_factor,e=Math.round(parseInt(c.style.left)/d),f=Math.round(parseInt(c.style.top)/d),g=Math.round(c.offsetWidth/d),d=Math.round(c.offsetHeight/d),e=zoom(e),f=zoom(f),g=zoom(g),d=zoom(d);0<g&&0<d&&(c.annotateUI_textProperties._zoom_factor=_zoom_factor,set_size(c.annotateUI_textProperties._nodeId+"-img",g,d),set_size(c,g,d),c.style.left=e+"px",c.style.top=f+"px");b++}a=a.nextSibling}annotateUI._update_state()}},cancelUI:function(){var a=
document.getElementById("annotateUI-panel");a&&(a.style.display="none")},createTextElement:function(a,b){a&&(a.x=zoom(a.x),a.y=zoom(a.y));var c=document.getElementById("textlayer");if(!(16<c.childNodes.length)){var d="text-node"+annotateUI._nextID;annotateUI._nextID++;var e=a?a:annotateUI._fetchTextProperties("addtext");if(!e)return!1;e._zoomfactor=_zoom_factor;e._nodeId=d;var f=d+"-img",g='<div class="sticker" id="'+d+'" onmouseover="annotateUI.showControls(\''+d+"')\" onmouseout=\"annotateUI.hideControls('"+
d+'\')" style="z-index:'+annotateUI._nextID+';"><div id="'+d+'-controls" class="sticker-controls"><a href="#" onClick="javascript:annotateUI.removeElement(\''+d+'\');return false;" class="sticker-remove"></a></div><img   id="'+f+'" onClick="annotateUI._setActiveElement(\''+d+'\');" class="sticker-img"></div>',h=document.createElement("div");h.innerHTML=g;c.appendChild(h);g=document.getElementById(d);if(!g)return!1;g.annotateUI_textProperties=e;request_sticker_image(g.annotateUI_textProperties);DragHandler.ondragbegin||
(DragHandler.ondragbegin=delegate(annotateUI,"_clear_state_timer"));DragHandler.ondragend||(DragHandler.ondragend=delegate(annotateUI,"_update_state"));DragHandler.attach(document.getElementById(f),c);annotateUI._setActiveElement(d);a?(g.style.left=a.x+"px",g.style.top=a.y+"px"):(g.style.left=parseInt(.15*c.offsetWidth)+"px",g.style.top=parseInt(.15*c.offsetHeight)+"px");b||annotateUI._update_state();if(c=document.getElementById("toolbar-download"))c.style.display="block";return!1}},addTextElement:function(){var a=
annotateUI._fetchTextProperties("addtext");annotateUI.createTextElement(a,1);annotateUI._update_state()},editTextElement:function(){if(!annotateUI._activeElement)return!1;var a=document.getElementById(annotateUI._activeElement);if(!a)return!1;var b=annotateUI._fetchTextProperties("addtext");if(!b)return!1;b._nodeId=a.annotateUI_textProperties._nodeId;a.annotateUI_textProperties=b;request_sticker_image(a.annotateUI_textProperties);annotateUI._update_state()},_imgURL:function(a){return"/sticker/text?tl_text0="+
encodeURIComponent(a.text)+"&tl_font0="+encodeURIComponent(a.font)+"&tl_size0="+encodeURIComponent(a.size)+"&tl_color0="+encodeURIComponent(a.color)+"&tl_extra0="+encodeURIComponent(a.extra)+"&tl_bold0="+encodeURIComponent(a.bold)+"&tl_italic0="+encodeURIComponent(a.italic)+"&tl_rot0="+encodeURIComponent(a.rot)+"&tl_backgroundcolor0="+encodeURIComponent(a.backgroundcolor)+"&tl_backgroundopacity0="+encodeURIComponent(a.backgroundopacity)+"&tl_count=1"},_fetchTextProperties:function(a){a={};var b=null;
if(b=document.getElementById("annotateUI-text"))a.text=b.value;if(!a.text)return null;if(b=document.getElementById("annotateUI-font"))a.font=b.value;if(b=document.getElementById("annotateUI-fontsize"))a.size=b.value;if(b=document.getElementById("annotateUI-color"))a.color=b.value;if(b=document.getElementById("annotateUI-bold"))a.bold=b.value;if(b=document.getElementById("annotateUI-italic"))a.italic=b.value;a.backgroundcolor=f_gval("annotateUI-backgroundcolor");a.backgroundopacity=f_gval("annotateUI-backgroundopacity");
a.rot=0;return a},_setActiveElement:function(a){if(annotateUI._activeElement=a)if(a=document.getElementById(a)){bringElementToTop(a);a=a.annotateUI_textProperties;f_sval("annotateUI-text",a.text);f_sval("annotateUI-fontsize",a.size);f_sval("annotateUI-font",a.font);f_sval("annotateUI-backgroundcolor",a.backgroundcolor);f_sval("annotateUI-backgroundopacity",a.backgroundopacity);var b=document.getElementById("annotateUI-color");b.color&&b.color.fromString?b.color.fromString(a.color):b.value=a.color}},
removeElement:function(a){if(a=document.getElementById(a)){try{a.parentNode.removeChild(a)}catch(b){throw"AnnotateUI::removeElement: "+b;}annotateUI._setActiveElement(null);annotateUI._update_state()}},showControls:function(a){if(a=document.getElementById(a+"-controls"))annotateUI._controlsTimerId&&(clearInterval(annotateUI._controlsTimerId),annotateUI._controlsTimerId=0),a.style.display="block"},hideControls:function(a){if(a=document.getElementById(a+"-controls"))a.style.display="none"},storeToForm:function(a){a=
document.getElementById(a);for(var b=document.getElementById("textlayer"),c=b.firstChild,d=0,e;c;){var f=c.firstChild;f&&f.annotateUI_textProperties&&(e=create_input_hidden(a,"tl_text"+d),e.value=f.annotateUI_textProperties.text,e=create_input_hidden(a,"tl_font"+d),e.value=f.annotateUI_textProperties.font,e=create_input_hidden(a,"tl_size"+d),e.value=f.annotateUI_textProperties.size,e=create_input_hidden(a,"tl_color"+d),e.value=f.annotateUI_textProperties.color,e=create_input_hidden(a,"tl_extra"+d),
e.value=f.annotateUI_textProperties.extra,e=create_input_hidden(a,"tl_rot"+d),e.value=f.annotateUI_textProperties.rot,e=create_input_hidden(a,"tl_x"+d),e.value=unzoom(parseInt(f.style.left)),e=create_input_hidden(a,"tl_y"+d),e.value=unzoom(parseInt(f.style.top)),e=create_input_hidden(a,"tl_backgroundcolor"+d),e.value=f.annotateUI_textProperties.backgroundcolor,e=create_input_hidden(a,"tl_backgroundopacity"+d),e.value=parseInt(f.annotateUI_textProperties.backgroundopacity),d++);c=c.nextSibling}d&&
(create_input_hidden(a,"tl_count").value=d,create_input_hidden(a,"tl_width").value=unzoom(b.offsetWidth),create_input_hidden(a,"tl_height").value=unzoom(b.offsetHeight))},_handle_download:function(a){annotateUI.storeToForm("downloadform");var b=document.getElementById("downloadform");b.action=a.href;b.submit()},_update_state:function(){annotateUI._clear_state_timer();annotateUI._stateTimerId=window.setTimeout(delegate(annotateUI,"_update_state_do"),800)},_clear_state_timer:function(){annotateUI._stateTimerId&&
(window.clearTimeout(annotateUI._stateTimerId),annotateUI._stateTimerId=0)},_update_state_do:function(){annotateUI._clear_state_timer();var a=document.getElementById("session-key");if(a&&a.value){var b=document.getElementById("sourceimage-cascade");if(b&&b.value){for(var c=document.getElementById("textlayer"),d=c.firstChild,a="sid="+encodeURIComponent(a.value),a=a+("&src="+encodeURIComponent(b.value)),b=0;d;){var e=d.firstChild;e&&e.annotateUI_textProperties&&(a+="&tl_text"+b+"="+encodeURIComponent(e.annotateUI_textProperties.text),
a+="&tl_font"+b+"="+encodeURIComponent(e.annotateUI_textProperties.font),a+="&tl_size"+b+"="+encodeURIComponent(e.annotateUI_textProperties.size),a+="&tl_color"+b+"="+encodeURIComponent(e.annotateUI_textProperties.color),a+="&tl_extra"+b+"="+encodeURIComponent(e.annotateUI_textProperties.extra),a+="&tl_rot"+b+"="+encodeURIComponent(e.annotateUI_textProperties.rot),a+="&tl_x"+b+"="+encodeURIComponent(unzoom(parseInt(e.style.left))),a+="&tl_y"+b+"="+encodeURIComponent(unzoom(parseInt(e.style.top))),
a+="&tl_backgroundcolor"+b+"="+encodeURIComponent(e.annotateUI_textProperties.backgroundcolor),a+="&tl_backgroundopacity"+b+"="+encodeURIComponent(e.annotateUI_textProperties.backgroundopacity),b++);d=d.nextSibling}a+="&tl_count="+encodeURIComponent(b);a+="&tl_width="+encodeURIComponent(unzoom(c.offsetWidth));a+="&tl_height="+encodeURIComponent(unzoom(c.offsetHeight));c=annotateUI._stateNotification;c.open("POST","/annotate/wst",!0);c.setRequestHeader("Content-type","application/x-www-form-urlencoded");
c.send(a)}}},init:function(){var a=annotateUI._stateFetcher,b=document.getElementById("session-key");if(b&&b.value){var c=document.getElementById("sourceimage-cascade");c&&c.value&&(b="sid="+encodeURIComponent(b.value),b+="&src="+encodeURIComponent(c.value),a.open("POST","/annotate/rst",!0),a.onreadystatechange=delegate(annotateUI,"init_do",a),a.setRequestHeader("Content-type","application/x-www-form-urlencoded"),a.send(b))}},init_do:function(a){if(a&&4==a.readyState&&200==a.status){var b=null;try{b=
JSON.parse(a.responseText)}catch(c){return}for(a=0;a<b.length;a++)annotateUI.createTextElement(b[a],1)}},showTextlayer:function(a){document.getElementById("textlayer").style.display=a?"block":"none"},resizeTextLayer:function(a,b,c,d,e,f){}};function create_input_hidden(a,b){if(a.elements[b])return a.elements[b];var c=document.createElement("input");c.type="hidden";c.name=b;a.appendChild(c);return c}addEvent(window,"load",delegate(annotateUI,"init"));var xmlhttp_subfiltersettings=new_xmlhttp();
function updatebackgroundfiltercontrols(a){a=a.value;if(!a)return!1;var b=document.getElementById("backgroundfilter-controls");b&&(b.style.display="none",b=xmlhttp_subfiltersettings,b.open("GET","/filter-controls/"+a,!0),b.onreadystatechange=subfilterctrls_onreadystatechange,b.send(null))}
function subfilterctrls_onreadystatechange(){var a=xmlhttp_subfiltersettings;if(a&&4==a.readyState&&200==a.status){var b=document.getElementById("backgroundfilter-controls");b&&(b.innerHTML=a.responseText,b.style.display="block",jscolor&&jscolor.init())}}
var QRU={_img:null,_imgW:0,_imgH:0,_timerId:0,_timerTimeoutDefault:220,_timerTimeout:220,enqueue:function(){QRU._timerId&&window.clearTimeout(QRU._timerId);QRU._timerId=window.setTimeout(delegate(QRU,"send_request"),QRU._timerTimeout)},send_request:function(){QRU._timerId&&window.clearTimeout(QRU._timerId);QRU._timerTimeout*=2.5;var a=document.getElementById("filter-settings-form");if(a){var b=new_xmlhttp();b&&(a=urlencode_form(a),a.length&&(TPEditorUI.showLoadIndicator(!0),b.open("POST","/qru/"+
wsEffect,!0),b.onreadystatechange=delegate(QRU,"onreadystatechange",b),b.setRequestHeader("Content-type","application/x-www-form-urlencoded"),b.send(a)))}},onreadystatechange:function(a){a&&4==a.readyState&&200==a.status&&(a=a.responseText.split(","),5==a.length&&(QRU._imgW=a[0],QRU._imgH=a[1],QRU._imgSK=a[2],QRU._imgFN=a[3],QRU._img=new Image,QRU._img.onload=delegate(QRU,"onload_render"),QRU._img.src="/image-sessions/"+a[2]+"/"+a[3]))},onload_render:function(){var a=document.getElementById("rendered-image");
document.getElementById("filter-settings-form");_original_image_width=QRU._imgW;_original_image_height=QRU._imgH;a.src=QRU._img.src;a.width=QRU._imgW;a.height=QRU._imgH;setStyle(a,"width:"+QRU._imgW+"px;height:"+QRU._imgH+"px");setStyle(document.getElementById("image-container"),"width:"+QRU._imgW+"px");setStyle(document.getElementById("image-container-wrapper"),"width:"+QRU._imgW+"px");setStyle(document.getElementById("textlayer"),"width:"+QRU._imgW+"px;height:"+QRU._imgH+"px");update_downloadlinks(QRU._imgSK+
"-"+QRU._imgFN);document.getElementById("sourceimage-cascade").value=QRU._imgFN;TPEditorUI.showLoadIndicator(!1);QRU._timerTimeout=QRU._timerTimeoutDefault;update_viewport()}};function qru_do(){TPEditorUI.cancelUI();annotateUI.storeToForm("filter-settings-form");QRU&&QRU.enqueue()}function currentOIID(){return document.getElementById("sourceimage-cascade").value}function currentRSID(){return document.getElementById("effect-cascade2").elements.rsid.value}
function psui(a){for(var b=0;b<a.length;b+=2){var c=document.getElementById(a[b]);if(c){var d=a[b+1];"color"==c.className||"color"==c.type?(c.value="#"+d,"color"!=c.type&&(c.style.backgroundColor="#"+a[b+1])):c.value=d}}qru_do();return!1}function mfsf_onsubmit(){annotateUI.storeToForm("filter-settings-form");return!0};
this.JSON||(this.JSON={});
(function(){function m(a){return 10>a?"0"+a:a}function r(a){t.lastIndex=0;return t.test(a)?'"'+a.replace(t,function(a){var c=v[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function p(a,k){var c,d,h,q,g=e,f,b=k[a];b&&"object"===typeof b&&"function"===typeof b.toJSON&&(b=b.toJSON(a));"function"===typeof l&&(b=l.call(k,a,b));switch(typeof b){case "string":return r(b);case "number":return isFinite(b)?String(b):"null";case "boolean":case "null":return String(b);case "object":if(!b)return"null";
e+=n;f=[];if("[object Array]"===Object.prototype.toString.apply(b)){q=b.length;for(c=0;c<q;c+=1)f[c]=p(c,b)||"null";h=0===f.length?"[]":e?"[\n"+e+f.join(",\n"+e)+"\n"+g+"]":"["+f.join(",")+"]";e=g;return h}if(l&&"object"===typeof l)for(q=l.length,c=0;c<q;c+=1)d=l[c],"string"===typeof d&&(h=p(d,b))&&f.push(r(d)+(e?": ":":")+h);else for(d in b)Object.hasOwnProperty.call(b,d)&&(h=p(d,b))&&f.push(r(d)+(e?": ":":")+h);h=0===f.length?"{}":e?"{\n"+e+f.join(",\n"+e)+"\n"+g+"}":"{"+f.join(",")+"}";e=g;return h}}
"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(a){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+m(this.getUTCMonth()+1)+"-"+m(this.getUTCDate())+"T"+m(this.getUTCHours())+":"+m(this.getUTCMinutes())+":"+m(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var u=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,t=
/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,n,v={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,k,c){var d;n=e="";if("number"===typeof c)for(d=0;d<c;d+=1)n+=" ";else"string"===typeof c&&(n=c);if((l=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON.stringify");return p("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,e){function c(a,d){var g,f,b=a[d];if(b&&"object"===typeof b)for(g in b)Object.hasOwnProperty.call(b,g)&&(f=c(b,g),void 0!==f?b[g]=f:delete b[g]);return e.call(a,d,b)}var d;u.lastIndex=0;u.test(a)&&(a=a.replace(u,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,
"")))return d=eval("("+a+")"),"function"===typeof e?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();
function FilterContext(d,e){this.setFilter(d);this.setDisplayCanvas(e);return this}FilterContext.prototype.setFilter=function(d){if(this.filter=d)d.context=this};FilterContext.prototype.init=function(){this.canvas||(this.canvas=document.createElement("canvas"))};FilterContext.prototype.setImage=function(d){this.image=d;this.imagedata_in=null;update()};FilterContext.prototype.setImageId=function(d){this.image=document.getElementById(d)};
FilterContext.prototype.setDisplayCanvas=function(d){this.display=d;this.imagedata_in=null};FilterContext.prototype.onFilterParameterChanged=function(){this.update_delayed()};FilterContext.prototype.onFilterFinished=function(){};
FilterContext.prototype.update=function(){if(this.filter&&this.image){var d=this.display,e=this.image;if(0<e.width){this.canvas||(this.canvas=document.createElement("canvas"),this.canvas.style.display="none");this.canvas.width=d.width;this.canvas.height=d.height;var a=e.offsetWidth,c=e.offsetHeight,b=this.canvas.getContext("2d");b.drawImage(e,0,0,this.canvas.width,this.canvas.height);this.imagedata_in=b.getImageData(0,0,this.canvas.width,this.canvas.height);a=this.imagedata_in.width;c=this.imagedata_in.height;
this.imagedata_out=b.createImageData(a,c);try{this.filter.process(this.imagedata_in,this.imagedata_out)}catch(f){throw"FilterContext:update error while in filter.process: "+f;}d&&d.getContext("2d").putImageData(this.imagedata_out,0,0)}}};FilterContext.prototype.update_delayed=function(){this.update()};function ColorFilter(){this.contrast=this.saturation=this.brightness=this.hue=0;return this}
function matrix_comb(d,e){var a=Array(20);a[0]=d[0]*e[0]+d[1]*e[5]+d[2]*e[10];a[1]=d[0]*e[1]+d[1]*e[6]+d[2]*e[11];a[2]=d[0]*e[2]+d[1]*e[7]+d[2]*e[12];a[3]=0;a[4]=e[4];a[5]=d[5]*e[0]+d[6]*e[5]+d[7]*e[10];a[6]=d[5]*e[1]+d[6]*e[6]+d[7]*e[11];a[7]=d[5]*e[2]+d[6]*e[7]+d[7]*e[12];a[8]=0;a[9]=e[9];a[10]=d[10]*e[0]+d[11]*e[5]+d[12]*e[10];a[11]=d[10]*e[1]+d[11]*e[6]+d[12]*e[11];a[12]=d[10]*e[2]+d[11]*e[7]+d[12]*e[12];a[13]=0;a[14]=e[12];a[15]=0;a[16]=0;a[17]=0;a[18]=1;a[19]=0;return a}
ColorFilter.prototype.setHue=function(d){this.hue=Math.min(Math.max(d,-1),1);if(this.context)this.context.onFilterParameterChanged()};ColorFilter.prototype.setSaturation=function(d){this.saturation=Math.min(Math.max(d,-1),2);if(this.context)this.context.onFilterParameterChanged()};ColorFilter.prototype.setBrightness=function(d){this.brightness=Math.min(Math.max(d,-1),1);if(this.context)this.context.onFilterParameterChanged()};
ColorFilter.prototype.setContrast=function(d){this.contrast=Math.min(Math.max(d,-1),2);if(this.context)this.context.onFilterParameterChanged()};
ColorFilter.prototype.process=function(d,e){var a=[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0],c=180*this.hue,c=.0174532925*c,b=Math.cos(c),c=Math.sin(c),f=[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0];f[0]=.213+.787*b+-.213*c;f[1]=.715+-.715*b+-.715*c;f[2]=.072+-.072*b+.928*c;f[5]=.213+-.212*b+.143*c;f[6]=.715+.285*b+.14*c;f[7]=.072+-.072*b+-.283*c;f[10]=.213+-.213*b+-.787*c;f[11]=.715+-.715*b+.715*c;f[12]=.072+.928*b+.072*c;a=matrix_comb(a,f);saturation=1+this.saturation;b=[1,0,0,0,0,0,1,0,0,0,0,0,1,0,
0,0,0,0,1,0];b[0]=.213+.787*saturation;b[1]=.715-.715*saturation;b[2]=.072-.072*saturation;b[5]=.213-.212*saturation;b[6]=.715+.285*saturation;b[7]=.072-.072*saturation;b[10]=.213-.213*saturation;b[11]=.715-.715*saturation;b[12]=.072+.928*saturation;a=matrix_comb(a,b);b=110*this.brightness;a[4]+=b;a[9]+=b;a[14]+=b;c=this.contrast;0>c&&(c*=50);0<c&&(c*=150);b=c;c/=100;a[0]+=c;a[4]-=b;a[6]+=c;a[9]-=b;a[12]+=c;a[14]-=b;for(var b=a[0],c=a[1],f=a[2],r=a[3],t=a[4],u=a[5],v=a[6],w=a[7],x=a[8],y=a[9],z=a[10],
A=a[11],B=a[12],C=a[13],D=a[14],E=a[15],F=a[16],G=a[17],H=a[18],a=a[19],m=d.data,n=e.data,h,k,l,p,g,q=0;q<m.length;q+=4)h=m[q],k=m[q+1],l=m[q+2],p=m[q+3],g=.05+.0028515625*(.213*h+.715*k+.072*l),n[q]=b*h+c*k+f*l+r*p+t*g,n[q+1]=u*h+v*k+w*l+x*p+y*g,n[q+2]=z*h+A*k+B*l+C*p+D*g,n[q+3]=E*h+F*k+G*l+H*p+a;e.data=n};
ColorFilter.prototype.process__=function(d,e){var a=[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0],c=180*this.hue,c=.0174532925*c,b=Math.cos(c),c=Math.sin(c),f=[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0];f[0]=.213+.787*b+-.213*c;f[1]=.715+-.715*b+-.715*c;f[2]=.072+-.072*b+.928*c;f[5]=.213+-.212*b+.143*c;f[6]=.715+.285*b+.14*c;f[7]=.072+-.072*b+-.283*c;f[10]=.213+-.213*b+-.787*c;f[11]=.715+-.715*b+.715*c;f[12]=.072+.928*b+.072*c;a=matrix_comb(a,f);saturation=1+this.saturation;b=[1,0,0,0,0,0,1,0,0,0,0,0,1,
0,0,0,0,0,1,0];b[0]=.213+.787*saturation;b[1]=.715-.715*saturation;b[2]=.072-.072*saturation;b[5]=.213-.212*saturation;b[6]=.715+.285*saturation;b[7]=.072-.072*saturation;b[10]=.213-.213*saturation;b[11]=.715-.715*saturation;b[12]=.072+.928*saturation;a=matrix_comb(a,b);b=110*this.brightness;a[4]+=b;a[9]+=b;a[14]+=b;c=this.contrast;0>c&&(c*=50);0<c&&(c*=150);b=c;c/=100;a[0]+=c;a[4]-=b;a[6]+=c;a[9]-=b;a[12]+=c;a[14]-=b;for(var b=a[0],c=a[1],f=a[2],r=a[3],t=a[4],u=a[5],v=a[6],w=a[7],x=a[8],y=a[9],z=
a[10],A=a[11],B=a[12],C=a[13],D=a[14],E=a[15],F=a[16],G=a[17],H=a[18],a=a[19],m=d.data,n=e.data,h,k,l,p,g=0;g<m.length;g+=4)h=m[g],k=m[g+1],l=m[g+2],p=m[g+3],n[g]=b*h+c*k+f*l+r*p+t,n[g+1]=u*h+v*k+w*l+x*p+y,n[g+2]=z*h+A*k+B*l+C*p+D,n[g+3]=E*h+F*k+G*l+H*p+a;e.data=n};
var hue_slider=null,saturation_slider=null,contrast_slider=null,brightness_slider=null,colorfilter,filtercontext;function ca_getimage(){return document.getElementById("rendered-image").src}
function color_adjust_update(){var a=document.getElementById("coloradjust");a&&"function"==typeof a.adjust_colors||(a=document.getElementById("coloradjust2"));var c=parseInt(hue_slider.getValue()-500),d=parseInt(brightness_slider.getValue()-500),e=parseInt(contrast_slider.getValue()-500),b=parseInt(saturation_slider.getValue());a&&"function"==typeof a.adjust_colors&&a.adjust_colors(c,b,d,e)}function supports_canvas(){return!!document.createElement("canvas").getContext}
function supports_input_range(){var a=document.createElement("input");a.setAttribute("type","range");return"text"!==a.type}function ismsie(){return 0<window.navigator.userAgent.indexOf("MSIE ")||navigator.userAgent.match(/Trident.*rv\:11\./)?!0:!1}function coloradjust_startUI(){TPEditorUI.cancelUI();supports_canvas()&&supports_input_range()&&!ismsie()?coloradjust_startUI_2():coloradjust_startUI_flash()}
function coloradjust_startUI_2(){var a=document.getElementById("toolbar-dropdown");if(!a)return!1;annotateUI.showTextlayer(!1);100<_zoom_value&&tp_set_zoom(100);a.innerHTML='<a href="#" onclick="TPEditorUI.cancelUI();return false" class="editor-panel-ctrlbar-close"></a><table id="ca-controls">\t\r\n<tr class="ca-controls-row">\t\r\n<td class="group">\r\n<div>\t\r\n<label for="ca-slider-brightness">Brightness:</label>\t\r\n<input id="ca-slider-brightness" type="range" value="0" min="-500" max="500" oninput="colorfilter.setBrightness( ((this.value) / ( this.max-this.min  )) / .5);" />\t\r\n</div>\t\r\n<div>\t\r\n<label for="ca-slider-saturation">Saturation:</label>\t\r\n<input id="ca-slider-saturation" type="range" value="0" min="-500" max="500" oninput="colorfilter.setSaturation( this.value / 500.0 );" />\t\r\n</div>\r\n</td>\r\n<td class="group">\r\n<div>\r\n<label for="ca-slider-hue">Hue:</label>\r\n<input id="ca-slider-hue" type="range" value="0" min="-50" max="50" oninput="colorfilter.setHue( ((this.value) / ( this.max-this.min  ))/.5 );" />\r\n</div>\r\n<div>\r\n<label for="ca-slider-contrast">Contrast:</label>\r\n<input id="ca-slider-contrast" type="range" value="0" min="-500" max="500" oninput="colorfilter.setContrast( ((this.value) / ( this.max-this.min  )) / .5);" />\r\n</div>\r\n</td>\r\n</tr>\r\n<tr class="ca-controls-row">\t\r\n<td class="group confirm" colspan="2">\r\n<button class="confirm" onclick="coloradjust_apply_2()">Apply</button>\r\n</td>\r\n</tr\r\n</table>';
a.style.display="block";var a=document.getElementById("rendered-image"),c=document.getElementById("ca-canvas");colorfilter=new ColorFilter;filtercontext=new FilterContext(colorfilter,c);filtercontext.setImageId("rendered-image");c.style.width=parseInt(1*a.offsetWidth)+"px";c.style.height=parseInt(1*a.offsetHeight)+"px";filtercontext.update();c.style.display="block"}
function coloradjust_startUI_flash(){var a=document.getElementById("toolbar-dropdown");if(!a)return!1;a.innerHTML='<a href="#" onclick="TPEditorUI.cancelUI();return false" class="editor-panel-ctrlbar-close"></a><div id="coloradjust-panel">\r\n<div id="coloradjust-controls">\r\n<div class="coloradjust-controls-set">\r\n<label>Brightness:</label>\r\n<div class="slider" id="brightness-slider">\r\n<input type="hidden" class="slider-input" id="brightness-slider-input">\r\n</div>\r\n<label>Contrast:</label>\r\n<div class="slider" id="contrast-slider">\r\n<input type="hidden" class="slider-input" id="contrast-slider-input">\r\n</div>\r\n</div>\r\n<div class="coloradjust-controls-set">\r\n<label>Saturation:</label>\r\n<div class="slider" id="saturation-slider">\r\n<input type="hidden" class="slider-input" id="saturation-slider-input">\r\n</div>\r\n<label>Hue:</label>\r\n<div class="slider" id="hue-slider">\r\n<input type="hidden" class="slider-input" id="hue-slider-input">\r\n</div>\r\n</div>\r\n<div>\r\n<button class="confirm" onclick="coloradjust_apply()">Apply</button>\r\n</div>\r\n</div><div id="coloradjust-preview"><object id="coloradjust" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="440" height="470">\r\n<param name="movie" value="/static/flash/coloradjust.swf"></param>\r\n<embed src="/static/flash/coloradjust.swf" width="440" height="470"\r\n allowscriptaccess="always" id="coloradjust2"></embed>\r\n</object></div><div class="clear"></div></div>';a.style.display=
"block";brightness_slider=new Slider(document.getElementById("brightness-slider"),document.getElementById("brightness-slider-input"));contrast_slider=new Slider(document.getElementById("contrast-slider"),document.getElementById("contrast-slider-input"));saturation_slider=new Slider(document.getElementById("saturation-slider"),document.getElementById("saturation-slider-input"));hue_slider=new Slider(document.getElementById("hue-slider"),document.getElementById("hue-slider-input"));hue_slider.onchange=
color_adjust_update;saturation_slider.onchange=color_adjust_update;brightness_slider.onchange=color_adjust_update;contrast_slider.onchange=color_adjust_update;hue_slider.setMinimum(0);hue_slider.setMaximum(1E3);hue_slider.setValue(500);brightness_slider.setMinimum(0);brightness_slider.setMaximum(1E3);brightness_slider.setValue(500);saturation_slider.setMinimum(0);saturation_slider.setMaximum(1E3);saturation_slider.setValue(500);contrast_slider.setMinimum(0);contrast_slider.setMaximum(1E3);contrast_slider.setValue(500)}
function coloradjust_apply(){var a=parseInt(hue_slider.getValue()-500),c=parseInt(brightness_slider.getValue()-500),d=parseInt(contrast_slider.getValue()-500),e=parseInt(saturation_slider.getValue()),b=document.getElementById("effect-cascade2");b.action="/photo-effects/coloradjust";var f=create_input_hidden(b,"efp_hue"),g=create_input_hidden(b,"efp_brightness"),h=create_input_hidden(b,"efp_contrast"),k=create_input_hidden(b,"efp_saturation");f.value=a;g.value=c;h.value=d;k.value=e;b.submit()}
function coloradjust_apply_2(){var a=parseInt(500*colorfilter.hue),c=parseInt(500*colorfilter.brightness),d=parseInt(500*colorfilter.contrast),e=parseInt(500*colorfilter.saturation+500),b=document.getElementById("effect-cascade2");b.action="/photo-effects/coloradjust";var f=create_input_hidden(b,"efp_hue"),g=create_input_hidden(b,"efp_brightness"),h=create_input_hidden(b,"efp_contrast"),k=create_input_hidden(b,"efp_saturation"),l=create_input_hidden(b,"efp_mode");f.value=a;g.value=c;h.value=d;k.value=
e;l.value=2;b.submit()};
/**
 * jscolor, JavaScript Color Picker
 *
 * @version 1.3.1
 * @license GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 * @author  Jan Odvarko, http://odvarko.cz
 * @created 2008-06-15
 * @updated 2010-01-23
 * @link    http://jscolor.com
 */
 /*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2014-12-09
 @link    http://jscolor.com
*/
var jscolor={dir:"/static/js/jscolor/",bindClass:"color",binding:!0,preloading:!0,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var b=jscolor.detectDir();jscolor.dir=!1!==b?b:"jscolor/"}return jscolor.dir},detectDir:function(){for(var b=location.href,f=document.getElementsByTagName("base"),c=0;c<f.length;c+=1)f[c].href&&(b=f[c].href);f=document.getElementsByTagName("script");
for(c=0;c<f.length;c+=1)if(f[c].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(f[c].src))return b=(new jscolor.URI(f[c].src)).toAbsolute(b),b.path=b.path.replace(/[^\/]+$/,""),b.query=null,b.fragment=null,b.toString();return!1},bind:function(){var b=new RegExp("(^|\\s)("+jscolor.bindClass+")(\\s*(\\{[^}]*\\})|\\s|$)","i"),f=document.getElementsByTagName("input");jscolor.isColorAttrSupported=!1;var c=document.createElement("input");c.setAttribute&&(c.setAttribute("type","color"),"color"==c.type.toLowerCase()&&
(jscolor.isColorAttrSupported=!0));for(c=0;c<f.length;c+=1)if(!jscolor.isColorAttrSupported||"color"!=f[c].type.toLowerCase()){var n;if(!f[c].color&&f[c].className&&(n=f[c].className.match(b))){var v={};if(n[4])try{v=(new Function("return ("+n[4]+")"))()}catch(A){}f[c].color=new jscolor.color(f[c],v)}}},preload:function(){for(var b in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(b)&&jscolor.loadImage(b)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},
requireImage:function(b){jscolor.imgRequire[b]=!0},loadImage:function(b){jscolor.imgLoaded[b]||(jscolor.imgLoaded[b]=new Image,jscolor.imgLoaded[b].src=jscolor.getDir()+b)},fetchElement:function(b){return"string"===typeof b?document.getElementById(b):b},addEvent:function(b,f,c){b.addEventListener?b.addEventListener(f,c,!1):b.attachEvent&&b.attachEvent("on"+f,c)},fireEvent:function(b,f){if(b)if(document.createEvent){var c=document.createEvent("HTMLEvents");c.initEvent(f,!0,!0);b.dispatchEvent(c)}else if(document.createEventObject)c=
document.createEventObject(),b.fireEvent("on"+f,c);else if(b["on"+f])b["on"+f]()},getElementPos:function(b){var f=b,c=0,n=0;if(f.offsetParent){do c+=f.offsetLeft,n+=f.offsetTop;while(f=f.offsetParent)}for(;(b=b.parentNode)&&"BODY"!==b.nodeName.toUpperCase();)c-=b.scrollLeft,n-=b.scrollTop;return[c,n]},getElementSize:function(b){return[b.offsetWidth,b.offsetHeight]},getRelMousePos:function(b){var f=0,c=0;b||(b=window.event);"number"===typeof b.offsetX?(f=b.offsetX,c=b.offsetY):"number"===typeof b.layerX&&
(f=b.layerX,c=b.layerY);return{x:f,y:c}},getViewPos:function(){return"number"===typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?
[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(b){function f(c){for(var b="";c;)if("../"===c.substr(0,3)||"./"===c.substr(0,2))c=c.replace(/^\.+/,"").substr(1);else if("/./"===c.substr(0,
3)||"/."===c)c="/"+c.substr(3);else if("/../"===c.substr(0,4)||"/.."===c)c="/"+c.substr(4),b=b.replace(/\/?[^\/]*$/,"");else if("."===c||".."===c)c="";else{var f=c.match(/^\/?[^\/]*/)[0];c=c.substr(f.length);b+=f}return b}this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(c){c=c.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=c[3]?c[2]:null;this.authority=c[5]?c[6]:null;this.path=c[7];this.query=c[9]?
c[10]:null;this.fragment=c[12]?c[13]:null;return this};this.toString=function(){var c="";null!==this.scheme&&(c=c+this.scheme+":");null!==this.authority&&(c=c+"//"+this.authority);null!==this.path&&(c+=this.path);null!==this.query&&(c=c+"?"+this.query);null!==this.fragment&&(c=c+"#"+this.fragment);return c};this.toAbsolute=function(c){c=new jscolor.URI(c);var b=new jscolor.URI;if(null===c.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===c.scheme.toLowerCase()&&(this.scheme=null);null!==
this.scheme?(b.scheme=this.scheme,b.authority=this.authority,b.path=f(this.path),b.query=this.query):(null!==this.authority?(b.authority=this.authority,b.path=f(this.path),b.query=this.query):(""===this.path?(b.path=c.path,b.query=null!==this.query?this.query:c.query):("/"===this.path.substr(0,1)?b.path=f(this.path):(b.path=null!==c.authority&&""===c.path?"/"+this.path:c.path.replace(/[^\/]+$/,"")+this.path,b.path=f(b.path)),b.query=this.query),b.authority=c.authority),b.scheme=c.scheme);b.fragment=
this.fragment;return b};b&&this.parse(b)},color:function(b,f){function c(a,c,b){if(null===a)return[b,b,b];var e=Math.floor(a),d=b*(1-c);a=b*(1-c*(e%2?a-e:1-(a-e)));switch(e){case 6:case 0:return[b,a,d];case 1:return[a,b,d];case 2:return[d,b,a];case 3:return[d,a,b];case 4:return[a,d,b];case 5:return[b,d,a]}}function n(a,c){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),
sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),btnS:document.createElement("span"),btnT:document.createTextNode(e.pickerCloseText)};for(var m=0;m<jscolor.images.sld[1];m+=4){var f=document.createElement("div");f.style.height="4px";f.style.fontSize="1px";f.style.lineHeight="0";jscolor.picker.sld.appendChild(f)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);
jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box)}var d=jscolor.picker;d.box.onmouseup=d.box.onmouseout=function(){b.focus()};d.box.onmousedown=
function(){w=!0};d.box.onmousemove=function(a){if(q||r)q&&B(a),r&&C(a),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),x()};"ontouchstart"in window&&(m=function(a){var c={offsetX:a.touches[0].pageX-t.X,offsetY:a.touches[0].pageY-t.Y};if(q||r)q&&B(c),r&&C(c),x();a.stopPropagation();a.preventDefault()},d.box.removeEventListener("touchmove",m,!1),d.box.addEventListener("touchmove",m,!1));d.padM.onmouseup=d.padM.onmouseout=function(){q&&(q=!1,
jscolor.fireEvent(k,"change"))};d.padM.onmousedown=function(a){switch(u){case 0:0===e.hsv[2]&&e.fromHSV(null,null,1);break;case 1:0===e.hsv[1]&&e.fromHSV(null,1,null)}r=!1;q=!0;B(a);x()};"ontouchstart"in window&&d.padM.addEventListener("touchstart",function(a){t={X:a.target.offsetParent.offsetLeft,Y:a.target.offsetParent.offsetTop};this.onmousedown({offsetX:a.touches[0].pageX-t.X,offsetY:a.touches[0].pageY-t.Y})});d.sldM.onmouseup=d.sldM.onmouseout=function(){r&&(r=!1,jscolor.fireEvent(k,"change"))};
d.sldM.onmousedown=function(a){q=!1;r=!0;C(a);x()};"ontouchstart"in window&&d.sldM.addEventListener("touchstart",function(a){t={X:a.target.offsetParent.offsetLeft,Y:a.target.offsetParent.offsetTop};this.onmousedown({offsetX:a.touches[0].pageX-t.X,offsetY:a.touches[0].pageY-t.Y})});m=v(e);d.box.style.width=m[0]+"px";d.box.style.height=m[1]+"px";d.boxB.style.position="absolute";d.boxB.style.clear="both";d.boxB.style.left=a+"px";d.boxB.style.top=c+"px";d.boxB.style.zIndex=e.pickerZIndex;d.boxB.style.border=
e.pickerBorder+"px solid";d.boxB.style.borderColor=e.pickerBorderColor;d.boxB.style.background=e.pickerFaceColor;d.pad.style.width=jscolor.images.pad[0]+"px";d.pad.style.height=jscolor.images.pad[1]+"px";d.padB.style.position="absolute";d.padB.style.left=e.pickerFace+"px";d.padB.style.top=e.pickerFace+"px";d.padB.style.border=e.pickerInset+"px solid";d.padB.style.borderColor=e.pickerInsetColor;d.padM.style.position="absolute";d.padM.style.left="0";d.padM.style.top="0";d.padM.style.width=e.pickerFace+
2*e.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";d.padM.style.height=d.box.style.height;d.padM.style.cursor="crosshair";d.sld.style.overflow="hidden";d.sld.style.width=jscolor.images.sld[0]+"px";d.sld.style.height=jscolor.images.sld[1]+"px";d.sldB.style.display=e.slider?"block":"none";d.sldB.style.position="absolute";d.sldB.style.right=e.pickerFace+"px";d.sldB.style.top=e.pickerFace+"px";d.sldB.style.border=e.pickerInset+"px solid";d.sldB.style.borderColor=e.pickerInsetColor;d.sldM.style.display=
e.slider?"block":"none";d.sldM.style.position="absolute";d.sldM.style.right="0";d.sldM.style.top="0";d.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+e.pickerFace+2*e.pickerInset+"px";d.sldM.style.height=d.box.style.height;try{d.sldM.style.cursor="pointer"}catch(l){d.sldM.style.cursor="hand"}d.btn.style.display=e.pickerClosable?"block":"none";d.btn.style.position="absolute";d.btn.style.left=e.pickerFace+"px";d.btn.style.bottom=e.pickerFace+"px";d.btn.style.padding="0 15px";d.btn.style.height=
"18px";d.btn.style.border=e.pickerInset+"px solid";(function(){var a=e.pickerInsetColor.split(/\s+/);d.btn.style.borderColor=2>a.length?a[0]:a[1]+" "+a[0]+" "+a[0]+" "+a[1]})();d.btn.style.color=e.pickerButtonColor;d.btn.style.font="12px sans-serif";d.btn.style.textAlign="center";try{d.btn.style.cursor="pointer"}catch(h){d.btn.style.cursor="hand"}d.btn.onmousedown=function(){e.hidePicker()};d.btnS.style.lineHeight=d.btn.style.height;switch(u){case 0:var g="hs.png";break;case 1:g="hv.png"}d.padM.style.backgroundImage=
"url('"+jscolor.getDir()+"cross.gif')";d.padM.style.backgroundRepeat="no-repeat";d.sldM.style.backgroundImage="url('"+jscolor.getDir()+"arrow.gif')";d.sldM.style.backgroundRepeat="no-repeat";d.pad.style.backgroundImage="url('"+jscolor.getDir()+g+"')";d.pad.style.backgroundRepeat="no-repeat";d.pad.style.backgroundPosition="0 0";A();G();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(d.boxB)}function v(a){return[2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[0]+(a.slider?
2*a.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),a.pickerClosable?4*a.pickerInset+3*a.pickerFace+jscolor.images.pad[1]+a.pickerButtonHeight:2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[1]]}function A(){switch(u){case 0:var a=1;break;case 1:a=2}var b=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),a=Math.round((1-e.hsv[a])*(jscolor.images.pad[1]-1));jscolor.picker.padM.style.backgroundPosition=e.pickerFace+e.pickerInset+b-Math.floor(jscolor.images.cross[0]/2)+"px "+(e.pickerFace+
e.pickerInset+a-Math.floor(jscolor.images.cross[1]/2))+"px";b=jscolor.picker.sld.childNodes;switch(u){case 0:for(var m=c(e.hsv[0],e.hsv[1],1),a=0;a<b.length;a+=1)b[a].style.backgroundColor="rgb("+m[0]*(1-a/b.length)*100+"%,"+m[1]*(1-a/b.length)*100+"%,"+m[2]*(1-a/b.length)*100+"%)";break;case 1:var f,d=[e.hsv[2],0,0],a=Math.floor(e.hsv[0]),l=a%2?e.hsv[0]-a:1-(e.hsv[0]-a);switch(a){case 6:case 0:m=[0,1,2];break;case 1:m=[1,0,2];break;case 2:m=[2,0,1];break;case 3:m=[2,1,0];break;case 4:m=[1,2,0];break;
case 5:m=[0,2,1]}for(a=0;a<b.length;a+=1)f=1-1/(b.length-1)*a,d[1]=d[0]*(1-f*l),d[2]=d[0]*(1-f),b[a].style.backgroundColor="rgb("+100*d[m[0]]+"%,"+100*d[m[1]]+"%,"+100*d[m[2]]+"%)"}}function G(){switch(u){case 0:var a=2;break;case 1:a=1}a=Math.round((1-e.hsv[a])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.arrow[1]/2))+"px"}function z(){return jscolor.picker&&jscolor.picker.owner===e}function H(){k!==b&&e.importColor()}
function B(a){var b=jscolor.getRelMousePos(a);a=b.x-e.pickerFace-e.pickerInset;b=b.y-e.pickerFace-e.pickerInset;switch(u){case 0:e.fromHSV(6/(jscolor.images.pad[0]-1)*a,1-b/(jscolor.images.pad[1]-1),null,D);break;case 1:e.fromHSV(6/(jscolor.images.pad[0]-1)*a,null,1-b/(jscolor.images.pad[1]-1),D)}}function C(a){a=jscolor.getRelMousePos(a).y-e.pickerFace-e.pickerInset;switch(u){case 0:e.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),E);break;case 1:e.fromHSV(null,1-a/(jscolor.images.sld[1]-1),null,
E)}}function x(){e.onImmediateChange&&("string"===typeof e.onImmediateChange?new Function(e.onImmediateChange):e.onImmediateChange).call(e)}this.adjust=this.required=!0;this.hash=!1;this.slider=this.caps=!0;this.styleElement=this.valueElement=b;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.minH=0;this.maxH=6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!0;this.pickerButtonHeight=
20;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=10;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var p in f)f.hasOwnProperty(p)&&(this[p]=f[p]);this.hidePicker=function(){z()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};
this.showPicker=function(){if(!z()){var a=jscolor.getElementPos(b),c=jscolor.getElementSize(b),e=jscolor.getViewPos(),f=jscolor.getViewSize(),d=v(this),l,h,g;switch(this.pickerPosition.toLowerCase()){case "left":l=1;h=0;g=-1;break;case "right":l=1;h=0;g=1;break;case "top":l=0;h=1;g=-1;break;default:l=0,g=h=1}var k=(c[h]+d[h])/2,a=this.pickerSmartPosition?[-e[l]+a[l]+d[l]>f[l]?-e[l]+a[l]+c[l]/2>f[l]/2&&0<=a[l]+c[l]-d[l]?a[l]+c[l]-d[l]:a[l]:a[l],-e[h]+a[h]+c[h]+d[h]-k+k*g>f[h]?-e[h]+a[h]+c[h]/2>f[h]/
2&&0<=a[h]+c[h]-k-k*g?a[h]+c[h]-k-k*g:a[h]+c[h]-k+k*g:0<=a[h]+c[h]-k+k*g?a[h]+c[h]-k+k*g:a[h]+c[h]-k-k*g]:[a[l],a[h]+c[h]-k+k*g];n(a[l],a[h])}};this.importColor=function(){k?this.adjust?!this.required&&/^\s*$/.test(k.value)?(k.value="",g.style.backgroundImage=g.jscStyle.backgroundImage,g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(y|F)):this.fromString(k.value)||this.exportColor():this.fromString(k.value,y)||(g.style.backgroundImage=g.jscStyle.backgroundImage,
g.style.backgroundColor=g.jscStyle.backgroundColor,g.style.color=g.jscStyle.color,this.exportColor(y|F)):this.exportColor()};this.exportColor=function(a){if(!(a&y)&&k){var c=this.toString();this.caps&&(c=c.toUpperCase());this.hash&&(c="#"+c);k.value=c}a&F||!g||(g.style.backgroundImage="none",g.style.backgroundColor="#"+this.toString(),g.style.color=.5>.213*this.rgb[0]+.715*this.rgb[1]+.072*this.rgb[2]?"#FFF":"#000");a&E||!z()||A();a&D||!z()||G()};this.fromHSV=function(a,b,e,f){null!==a&&(a=Math.max(0,
this.minH,Math.min(6,this.maxH,a)));null!==b&&(b=Math.max(0,this.minS,Math.min(1,this.maxS,b)));null!==e&&(e=Math.max(0,this.minV,Math.min(1,this.maxV,e)));this.rgb=c(null===a?this.hsv[0]:this.hsv[0]=a,null===b?this.hsv[1]:this.hsv[1]=b,null===e?this.hsv[2]:this.hsv[2]=e);this.exportColor(f)};this.fromRGB=function(a,b,e,f){null!==a&&(a=Math.max(0,Math.min(1,a)));null!==b&&(b=Math.max(0,Math.min(1,b)));null!==e&&(e=Math.max(0,Math.min(1,e)));a=null===a?this.rgb[0]:a;b=null===b?this.rgb[1]:b;var d=
null===e?this.rgb[2]:e,g=Math.min(Math.min(a,b),d);e=Math.max(Math.max(a,b),d);var h=e-g;0===h?a=[null,0,e]:(a=a===g?3+(d-b)/h:b===g?5+(a-d)/h:1+(b-a)/h,a=[6===a?0:a,h/e,e]);null!==a[0]&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,a[0])));0!==a[2]&&(this.hsv[1]=null===a[1]?null:Math.max(0,this.minS,Math.min(1,this.maxS,a[1])));this.hsv[2]=null===a[2]?null:Math.max(0,this.minV,Math.min(1,this.maxV,a[2]));a=c(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=a[0];this.rgb[1]=a[1];this.rgb[2]=
a[2];this.exportColor(f)};this.fromString=function(a,b){var c=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return c?(6===c[1].length?this.fromRGB(parseInt(c[1].substr(0,2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+
(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var e=this,u="hvs"===this.pickerMode.toLowerCase()?1:0,w=!1,k=jscolor.fetchElement(this.valueElement),g=jscolor.fetchElement(this.styleElement),q=!1,r=!1,t={},y=1,F=2,E=4,D=8;jscolor.isColorAttrSupported=!1;p=document.createElement("input");p.setAttribute&&(p.setAttribute("type","color"),"color"==p.type.toLowerCase()&&(jscolor.isColorAttrSupported=!0));jscolor.addEvent(b,"focus",function(){e.pickerOnfocus&&
e.showPicker()});jscolor.addEvent(b,"blur",function(){w?w=!1:window.setTimeout(function(){w||(k===b&&e.importColor(),e.pickerOnfocus&&e.hidePicker());w=!1},0)});k&&(p=function(){e.fromString(k.value,y);x()},jscolor.addEvent(k,"keyup",p),jscolor.addEvent(k,"input",p),jscolor.addEvent(k,"blur",H),k.setAttribute("autocomplete","off"));g&&(g.jscStyle={backgroundImage:g.style.backgroundImage,backgroundColor:g.style.backgroundColor,color:g.style.color});switch(u){case 0:jscolor.requireImage("hs.png");break;
case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}};jscolor.install();

/* END JS Color */
/*----------------------------------------------------------------------------\
|                                Slider 1.02                                  |
|-----------------------------------------------------------------------------|
|                         Created by Erik Arvidsson                           |
|                  (http://webfx.eae.net/contact.html#erik)                   |
|                      For WebFX (http://webfx.eae.net/)                      |
|-----------------------------------------------------------------------------|
|                Copyright (c) 2002, 2003, 2006 Erik Arvidsson                |
|-----------------------------------------------------------------------------|
| Licensed under the Apache License, Version 2.0 (the "License"); you may not |
| use this file except in compliance with the License.  You may obtain a copy |
| of the License at http://www.apache.org/licenses/LICENSE-2.0                |
|----------------------------------------------------------------------------*/
function Range(){this._minimum=this._value=0;this._maximum=100;this._extent=0;this._isChanging=!1}Range.prototype.setValue=function(a){a=Math.round(parseFloat(a));if(!isNaN(a)&&this._value!=a&&(this._value=a+this._extent>this._maximum?this._maximum-this._extent:a<this._minimum?this._minimum:a,!this._isChanging&&"function"==typeof this.onchange))this.onchange()};Range.prototype.getValue=function(){return this._value};
Range.prototype.setExtent=function(a){if(this._extent!=a&&(this._extent=0>a?0:this._value+a>this._maximum?this._maximum-this._value:a,!this._isChanging&&"function"==typeof this.onchange))this.onchange()};Range.prototype.getExtent=function(){return this._extent};
Range.prototype.setMinimum=function(a){if(this._minimum!=a){var b=this._isChanging;this._isChanging=!0;this._minimum=a;a>this._value&&this.setValue(a);a>this._maximum&&(this._extent=0,this.setMaximum(a),this.setValue(a));a+this._extent>this._maximum&&(this._extent=this._maximum-this._minimum);this._isChanging=b;if(!this._isChanging&&"function"==typeof this.onchange)this.onchange()}};Range.prototype.getMinimum=function(){return this._minimum};
Range.prototype.setMaximum=function(a){if(this._maximum!=a){var b=this._isChanging;this._isChanging=!0;this._maximum=a;a<this._value&&this.setValue(a-this._extent);a<this._minimum&&(this._extent=0,this.setMinimum(a),this.setValue(this._maximum));a<this._minimum+this._extent&&(this._extent=this._maximum-this._minimum);a<this._value+this._extent&&(this._extent=this._maximum-this._value);this._isChanging=b;if(!this._isChanging&&"function"==typeof this.onchange)this.onchange()}};
Range.prototype.getMaximum=function(){return this._maximum};
function Timer(a){this._pauseTime="undefined"==typeof a?1E3:a;this._timer=null;this._isStarted=!1}Timer.prototype.start=function(){this.isStarted()&&this.stop();var a=this;this._timer=window.setTimeout(function(){if("function"==typeof a.ontimer)a.ontimer()},this._pauseTime);this._isStarted=!1};Timer.prototype.stop=function(){null!=this._timer&&window.clearTimeout(this._timer);this._isStarted=!1};Timer.prototype.isStarted=function(){return this._isStarted};Timer.prototype.getPauseTime=function(){return this._pauseTime};
Timer.prototype.setPauseTime=function(a){this._pauseTime=a};
Slider.isSupported="undefined"!=typeof document.createElement&&"undefined"!=typeof document.documentElement&&"number"==typeof document.documentElement.offsetWidth;
function Slider(a,b,c){if(a){this._orientation=c||"horizontal";this._range=new Range;this._range.setExtent(0);this._blockIncrement=10;this._unitIncrement=1;this._timer=new Timer(100);Slider.isSupported&&a&&(this.document=a.ownerDocument||a.document,this.element=a,this.element.slider=this,this.element.unselectable="on",this.element.className=this._orientation+" "+this.classNameTag+" "+this.element.className,this.line=this.document.createElement("DIV"),this.line.className="line",this.line.unselectable=
"on",this.line.appendChild(this.document.createElement("DIV")),this.element.appendChild(this.line),this.handle=this.document.createElement("DIV"),this.handle.className="handle",this.handle.unselectable="on",this.handle.appendChild(this.document.createElement("DIV")),this.handle.firstChild.appendChild(this.document.createTextNode(String.fromCharCode(160))),this.element.appendChild(this.handle));this.input=b;var d=this;this._range.onchange=function(){d.recalculate();if("function"==typeof d.onchange)d.onchange()};
Slider.isSupported&&a?(this.element.onfocus=Slider.eventHandlers.onfocus,this.element.onblur=Slider.eventHandlers.onblur,this.element.onmousedown=Slider.eventHandlers.onmousedown,this.element.onmouseover=Slider.eventHandlers.onmouseover,this.element.onmouseout=Slider.eventHandlers.onmouseout,this.element.onkeydown=Slider.eventHandlers.onkeydown,this.element.onkeypress=Slider.eventHandlers.onkeypress,this.element.onmousewheel=Slider.eventHandlers.onmousewheel,this.handle.onselectstart=this.element.onselectstart=
function(){return!1},this._timer.ontimer=function(){d.ontimer()},window.setTimeout(function(){d.recalculate()},1)):this.input.onchange=function(a){d.setValue(d.input.value)}}}
Slider.eventHandlers={getEvent:function(a,b){a||(a=b?b.document.parentWindow.event:window.event);if(!a.srcElement){for(b=a.target;null!=b&&1!=b.nodeType;)b=b.parentNode;a.srcElement=b}"undefined"==typeof a.offsetX&&(a.offsetX=a.layerX,a.offsetY=a.layerY);return a},getDocument:function(a){return a.target?a.target.ownerDocument:a.srcElement.document},getSlider:function(a){for(a=a.target||a.srcElement;null!=a&&null==a.slider;)a=a.parentNode;return a?a.slider:null},getLine:function(a){for(a=a.target||
a.srcElement;null!=a&&"line"!=a.className;)a=a.parentNode;return a},getHandle:function(a){a=a.target||a.srcElement;for(var b=/handle/;null!=a&&!b.test(a.className);)a=a.parentNode;return a},onfocus:function(a){a=this.slider;a._focused=!0;a.handle.className="handle hover"},onblur:function(a){a=this.slider;a._focused=!1;a.handle.className="handle"},onmouseover:function(a){a=Slider.eventHandlers.getEvent(a,this);var b=this.slider;a.srcElement==b.handle&&(b.handle.className="handle hover")},onmouseout:function(a){a=
Slider.eventHandlers.getEvent(a,this);var b=this.slider;a.srcElement!=b.handle||b._focused||(b.handle.className="handle")},onmousedown:function(a){a=Slider.eventHandlers.getEvent(a,this);var b=this.slider;b.element.focus&&b.element.focus();Slider._currentInstance=b;var c=b.document;c.addEventListener?(c.addEventListener("mousemove",Slider.eventHandlers.onmousemove,!0),c.addEventListener("mouseup",Slider.eventHandlers.onmouseup,!0)):c.attachEvent&&(c.attachEvent("onmousemove",Slider.eventHandlers.onmousemove),
c.attachEvent("onmouseup",Slider.eventHandlers.onmouseup),c.attachEvent("onlosecapture",Slider.eventHandlers.onmouseup),b.element.setCapture());Slider.eventHandlers.getHandle(a)?Slider._sliderDragData={screenX:a.screenX,screenY:a.screenY,dx:a.screenX-b.handle.offsetLeft,dy:a.screenY-b.handle.offsetTop,startValue:b.getValue(),slider:b}:(c=Slider.eventHandlers.getLine(a),b._mouseX=a.offsetX+(c?b.line.offsetLeft:0),b._mouseY=a.offsetY+(c?b.line.offsetTop:0),b._increasing=null,b.ontimer())},onmousemove:function(a){a=
Slider.eventHandlers.getEvent(a,this);if(Slider._sliderDragData){var b=Slider._sliderDragData.slider,c=b.getMaximum()-b.getMinimum(),d,e;"horizontal"==b._orientation?(d=b.element.offsetWidth-b.handle.offsetWidth,e=a.screenX-Slider._sliderDragData.dx,a=100<Math.abs(a.screenY-Slider._sliderDragData.screenY)):(d=b.element.offsetHeight-b.handle.offsetHeight,e=b.element.offsetHeight-b.handle.offsetHeight-(a.screenY-Slider._sliderDragData.dy),a=100<Math.abs(a.screenX-Slider._sliderDragData.screenX));b.setValue(a?
Slider._sliderDragData.startValue:b.getMinimum()+c*e/d);return!1}b=Slider._currentInstance;null!=b&&(c=Slider.eventHandlers.getLine(a),b._mouseX=a.offsetX+(c?b.line.offsetLeft:0),b._mouseY=a.offsetY+(c?b.line.offsetTop:0))},onmouseup:function(a){Slider.eventHandlers.getEvent(a,this);a=Slider._currentInstance;var b=a.document;b.removeEventListener?(b.removeEventListener("mousemove",Slider.eventHandlers.onmousemove,!0),b.removeEventListener("mouseup",Slider.eventHandlers.onmouseup,!0)):b.detachEvent&&
(b.detachEvent("onmousemove",Slider.eventHandlers.onmousemove),b.detachEvent("onmouseup",Slider.eventHandlers.onmouseup),b.detachEvent("onlosecapture",Slider.eventHandlers.onmouseup),a.element.releaseCapture());Slider._sliderDragData?Slider._sliderDragData=null:(a._timer.stop(),a._increasing=null);Slider._currentInstance=null},onkeydown:function(a){a=Slider.eventHandlers.getEvent(a,this);var b=this.slider;a=a.keyCode;switch(a){case 33:b.setValue(b.getValue()+b.getBlockIncrement());break;case 34:b.setValue(b.getValue()-
b.getBlockIncrement());break;case 35:b.setValue("horizontal"==b.getOrientation()?b.getMaximum():b.getMinimum());break;case 36:b.setValue("horizontal"==b.getOrientation()?b.getMinimum():b.getMaximum());break;case 38:case 39:b.setValue(b.getValue()+b.getUnitIncrement());break;case 37:case 40:b.setValue(b.getValue()-b.getUnitIncrement())}if(33<=a&&40>=a)return!1},onkeypress:function(a){a=Slider.eventHandlers.getEvent(a,this);a=a.keyCode;if(33<=a&&40>=a)return!1},onmousewheel:function(a){a=Slider.eventHandlers.getEvent(a,
this);var b=this.slider;if(b._focused)return b.setValue(b.getValue()+a.wheelDelta/120*b.getUnitIncrement()),!1}};Slider.prototype.classNameTag="dynamic-slider-control";Slider.prototype.setValue=function(a){this._range.setValue(a);this.input.value=this.getValue()};Slider.prototype.getValue=function(){return this._range.getValue()};Slider.prototype.setMinimum=function(a){this._range.setMinimum(a);this.input.value=this.getValue()};Slider.prototype.getMinimum=function(){return this._range.getMinimum()};
Slider.prototype.setMaximum=function(a){this._range.setMaximum(a);this.input.value=this.getValue()};Slider.prototype.getMaximum=function(){return this._range.getMaximum()};Slider.prototype.setUnitIncrement=function(a){this._unitIncrement=a};Slider.prototype.getUnitIncrement=function(){return this._unitIncrement};Slider.prototype.setBlockIncrement=function(a){this._blockIncrement=a};Slider.prototype.getBlockIncrement=function(){return this._blockIncrement};Slider.prototype.getOrientation=function(){return this._orientation};
Slider.prototype.setOrientation=function(a){a!=this._orientation&&(Slider.isSupported&&this.element&&(this.element.className=this.element.className.replace(this._orientation,a)),this._orientation=a,this.recalculate())};
Slider.prototype.recalculate=function(){if(Slider.isSupported&&this.element){var a=this.element.offsetWidth,b=this.element.offsetHeight,c=this.handle.offsetWidth,d=this.handle.offsetHeight,e=this.line.offsetWidth,f=this.line.offsetHeight;"horizontal"==this._orientation?(this.handle.style.left=(a-c)*(this.getValue()-this.getMinimum())/(this.getMaximum()-this.getMinimum())+"px",this.handle.style.top=(b-d)/2+"px",this.line.style.top=(b-f)/2+"px",this.line.style.left=c/2+"px",this.line.style.width=Math.max(0,
a-c-2)+"px",this.line.firstChild.style.width=Math.max(0,a-c-4)+"px"):(this.handle.style.left=(a-c)/2+"px",this.handle.style.top=b-d-(b-d)*(this.getValue()-this.getMinimum())/(this.getMaximum()-this.getMinimum())+"px",this.line.style.left=(a-e)/2+"px",this.line.style.top=d/2+"px",this.line.style.height=Math.max(0,b-d-2)+"px",this.line.firstChild.style.height=Math.max(0,b-d-4)+"px")}};
Slider.prototype.ontimer=function(){var a=this.handle.offsetWidth,b=this.handle.offsetHeight,c=this.handle.offsetLeft,d=this.handle.offsetTop;"horizontal"==this._orientation?this._mouseX>c+a&&(null==this._increasing||this._increasing)?(this.setValue(this.getValue()+this.getBlockIncrement()),this._increasing=!0):this._mouseX<c&&(null==this._increasing||!this._increasing)&&(this.setValue(this.getValue()-this.getBlockIncrement()),this._increasing=!1):this._mouseY>d+b&&(null==this._increasing||!this._increasing)?
(this.setValue(this.getValue()-this.getBlockIncrement()),this._increasing=!1):this._mouseY<d&&(null==this._increasing||this._increasing)&&(this.setValue(this.getValue()+this.getBlockIncrement()),this._increasing=!0);this._timer.start()};

/* END Slider */
